version: '2'

services:
  couchbase:
    container_name: couchbase
    hostname: couchbase
    image: couchbase
    volumes:
      - ~/couchbase/data:/opt/couchbase/var
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210


